version: '3'

services:
  mongo:
    image: mongo
    container_name: database_mqtt
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo_admin_mqtt
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # backend:
  #   container_name: backend
  #   build: ./backend
  #   volumes:
  #     - ./backend:/src
  #     - nodemodules:/src/node_modules
  #   command: node index.js
  #   restart: always
  #   depends_on:
  #     - mongo

volumes:
  nodemodules: {}
